name: wafi
description: Finance Application
publish_to: 'Gustavo Alejandro Santaella Machado'
version: 5.3.2+17

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter_launcher_icons: ^0.9.0
  carousel_slider: ^4.2.1
  # flutter_baseflow_permissions: ^0.0.2
  flutter:
    sdk: flutter
  http: ^0.13.5
  provider: ^6.0.5
  search_choices: ^2.2.5
  dropdown_search: 5.0.6
  sqflite: 
  table_calendar: ^3.0.9
  fl_chart:
  flutter_circle_color_picker: ^0.3.0
  pie_chart: ^5.3.2
  syncfusion_flutter_charts:
  hive: ^2.2.3
  permission_handler: ^10.2.0
  path_provider: ^2.0.14
  logger: ^1.3.0
  intl: ^0.18.1
  cron: ^0.5.1
  flutter_local_notifications: ^14.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - "assets/app_icon.png"

flutter_icons:
  image_path: "assets/app_icon.png"
  android: true
  ios: true
  remove_alpha_ios: true
  resize_behavior: shrink_only
  adaptive_icon_background: "#38b6ff"
  adaptive_icon_foreground: "assets/app_icon.png"
  android_icons:
    - icon: "assets/app_icon.png"
      size: "192x192"
      density: "3.0"
    - icon: "assets/app_icon.png"
      size: "512x512"
      density: "4.0"
  ios_icons:
    - icon: "assets/app_icon.png"
      size: "1024x1024"
