name: finance
description: Finance Application
publish_to: 'Gustavo Alejandro Santaella Machado'
version: 2.0.0+3

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter_launcher_icons: ^0.9.0
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  http: ^0.13.5
  provider: ^6.0.5
  search_choices: ^2.2.5
  sqflite: 
  table_calendar: ^3.0.9
  fl_chart:
  flutter_circle_color_picker: ^0.3.0
  pie_chart: ^5.3.2
  syncfusion_flutter_charts:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - "assets/app_icon.png"

flutter_icons:
  image_path: "assets/app_icon.png"
  android: true
  ios: true
  remove_alpha_ios: true
  resize_behavior: shrink_only
  adaptive_icon_background: "#38b6ff"
  adaptive_icon_foreground: "assets/app_icon.png"
  android_icons:
    - icon: "assets/app_icon.png"
      size: "192x192"
      density: "3.0"
    - icon: "assets/app_icon.png"
      size: "512x512"
      density: "4.0"
  ios_icons:
    - icon: "assets/app_icon.png"
      size: "1024x1024"
